[build.environment]
HUGO_VERSION = "0.137.1"
TZ = "Asia/Tokyo"

[build]
publish = "public"
command = "npm run build"

[[redirects]]
  from = "https://oscal-japan.org/*"
  to = "https://www.oscal-japan.org/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "http://oscal-japan.org/*"
  to = "https://www.oscal-japan.org/:splat"
  status = 301
  force = true
